---
- name: add MariaDB repo
  copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo

- name: install packages
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python
    - MariaDB-server
    - MariaDB-client

- name: start mariadb
  service:
    name: mariadb
    state: started

- name: change mysql root password
  mysql_user:
    name: root 
    host: "{{ item }}" 
    password: "{{ db.root_pass }}"
    login_user: root
    login_password: "{{ db.root_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_eth0.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost 

- name: set up .my.cnf
  template: src=my.cnf.j2 dest='~/.my.cnf' 

- name: delete non existing mysql user
  mysql_user: name='' state=absent

- name: delete anonymous MySQL server user for {{ ansible_hostname }}
  mysql_user: user="" host="{{ ansible_hostname }}" state="absent"
 
- name: remove the MySQL test database
  mysql_db:
    db: test 
    state: absent
    login_user: root
    login_password: "{{ db.root_pass }}"

- name: create clustercheck
  template: src=clustercheck_sysconfig dest=/etc/sysconfig/clustercheck
