---
- name: install rdo-release
  yum: name=https://rdoproject.org/repos/rdo-release.rpm state=present

- name: install packages
  yum:
      name: "{{ item }}"
      state: latest
  with_items:
      - qemu-kvm 
      - qemu-img 
      - libvirt 
      - libvirt-python 
      - libvirt-client 
      - virt-install 
      - bridge-utils 
      - libguestfs-tools

- name: start libvirtd
  service:
      name: libvirtd
      state: started

