---
- name: Install prerequisites on all hosts
  hosts: am_hosts,pm_hosts,logging_hosts
  remote_user: centos
  become: yes
  tags:
    - prereqs
  roles:
    - repos
    - chrony

- name: Install Redis
  hosts: redis_hosts
  remote_user: centos
  become: yes
  tags:
    - availability
    - redis
  roles:
    - redis/server

- name: Install RabbitMQ
  hosts: rabbit_hosts
  remote_user: centos
  become: yes
  tags:
    - availability
    - rabbitmq
  roles:
    - rabbitmq/server

- name: Install Sensu
  hosts: sensu_hosts
  remote_user: centos
  become: yes
  tags:
    - availability
    - sensu
  roles:
    - sensu/server

- name: Install Uchiwa
  hosts: uchiwa_hosts
  remote_user: centos
  become: yes
  tags:
    - availability
    - uchiwa
    - web
  roles:
    - uchiwa

- name: Install Grafana
  hosts: grafana_hosts
  remote_user: centos
  become: yes
  tags:
    - performance
    - grafana
  roles:
    - grafana

- name: Install Sensu clients
  hosts: base
  remote_user: centos
  become: yes
  tags:
    - sensu_client
  roles:
    - sensu/client

#- name: Install ElasticSearch
#  hosts: elastic_hosts
#  tags:
#    - logging
#    - elasticsearch
#  roles:
#    - elasticsearch
#
#- name: Install Fluentd
#  hosts: fluent_hosts
#  tags:
#    - logging
#    - fluentd
#  roles:
#    - fluentd/server
#    - fluentd/syslog
#    - fluentd/elasticsearch
#
#- name: Install Kibana
#  hosts: kibana_hosts
#  tags:
#    - logging
#    - kibana
#    - web
#  roles:
#    - kibana/server
#    - kibana/proxy
#
#- name: Create firewall rules
#  hosts: all
#  tags:
#    - firewall
#  roles:
#    - firewall/commit
#
#- name: Install CollectD
#  hosts: collectd_hosts
#  roles:
#    - collectd
