---
- name: Install uchiwa configuration for Apache
  template:
    src: uchiwa.conf.j2
    dest: '{{ uchiwa_httpd_conf }}'
  notify: restart httpd

- name: Create uchiwa htpasswd file
  tags:
    - skip_ansible_lint  # ignore ANSIBLE0012
  command: >
    htpasswd -cb {{ uchiwa_proxy_htpasswd }} {{ uchiwa_proxy_user }}
    {{ uchiwa_proxy_pass }}
  notify: restart httpd

- name: Secure uchiwa htpasswd file
  file:
    path: '{{ uchiwa_proxy_htpasswd }}'
    owner: apache
    group: apache
    mode: 0640

- name: Configure default redirect
  copy:
    content: |
      RewriteRule ^/$ {{ uchiwa_path }} [R=302]
    dest: '{{ opstools_default_redirect_file }}'
    force: false
  notify: restart httpd
